/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";

// Create Virtual Routes

const OrderLazyImport = createFileRoute("/order")();

// Create/Update Routes

const OrderLazyRoute = OrderLazyImport.update({
  path: "/order",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/order.lazy").then((d) => d.Route));

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/order": {
      id: "/order";
      path: "/order";
      fullPath: "/order";
      preLoaderRoute: typeof OrderLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/order": typeof OrderLazyRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/order": typeof OrderLazyRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/order": typeof OrderLazyRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/order";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/order";
  id: "__root__" | "/" | "/order";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  OrderLazyRoute: typeof OrderLazyRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrderLazyRoute: OrderLazyRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/order"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/order": {
      "filePath": "order.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
