/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexLayzImport } from './routes/index.layz'

// Create Virtual Routes

const OrderLazyImport = createFileRoute('/order')()

// Create/Update Routes

const OrderLazyRoute = OrderLazyImport.update({
  path: '/order',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/order.lazy').then((d) => d.Route))

const IndexLayzRoute = IndexLayzImport.update({
  path: '/index/layz',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderLazyImport
      parentRoute: typeof rootRoute
    }
    '/index/layz': {
      id: '/index/layz'
      path: '/index/layz'
      fullPath: '/index/layz'
      preLoaderRoute: typeof IndexLayzImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/order': typeof OrderLazyRoute
  '/index/layz': typeof IndexLayzRoute
}

export interface FileRoutesByTo {
  '/order': typeof OrderLazyRoute
  '/index/layz': typeof IndexLayzRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/order': typeof OrderLazyRoute
  '/index/layz': typeof IndexLayzRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/order' | '/index/layz'
  fileRoutesByTo: FileRoutesByTo
  to: '/order' | '/index/layz'
  id: '__root__' | '/order' | '/index/layz'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  OrderLazyRoute: typeof OrderLazyRoute
  IndexLayzRoute: typeof IndexLayzRoute
}

const rootRouteChildren: RootRouteChildren = {
  OrderLazyRoute: OrderLazyRoute,
  IndexLayzRoute: IndexLayzRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/order",
        "/index/layz"
      ]
    },
    "/order": {
      "filePath": "order.lazy.jsx"
    },
    "/index/layz": {
      "filePath": "index.layz.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
